// <auto-generated />
using MVC_CrudIslemleri_Personel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_CrudIslemleri_Personel.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20220510133807_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_CrudIslemleri_Personel.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("MVC_CrudIslemleri_Personel.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Muhasabe"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bilgi İşlem"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Pazarlama"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Planlama ve Yönetim"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Lojistik"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "İdari"
                        });
                });

            modelBuilder.Entity("MVC_CrudIslemleri_Personel.Models.Calisan", b =>
                {
                    b.HasOne("MVC_CrudIslemleri_Personel.Models.Departman", "Departman")
                        .WithMany("Calisanlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("MVC_CrudIslemleri_Personel.Models.Departman", b =>
                {
                    b.Navigation("Calisanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
